name: Python application workflow
on: 
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@main
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@main
      env:
        DEP_PATH: requirements.txt
